/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package monopoly;

/**
 *
 * @author Ismail F Aziz
 */
public class NewGame extends javax.swing.JFrame {

    /**
     * Creates new form NewGame
     */
    public NewGame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPlayerCombo = new javax.swing.JComboBox<>();
        numPlayerText = new javax.swing.JLabel();
        player1Field = new javax.swing.JTextField();
        player2Field = new javax.swing.JTextField();
        player3Field = new javax.swing.JTextField();
        player4Field = new javax.swing.JTextField();
        okButton = new javax.swing.JButton();
        gunung = new javax.swing.JLabel();
        playerNameText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPlayerCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "1 Player", "2 Players", "3 Players", "4 Players" }));
        jPlayerCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPlayerComboActionPerformed(evt);
            }
        });

        numPlayerText.setText("Number of player(s) :");

        player1Field.setText("Player 1 Name");
        player1Field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                player1FieldFocusGained(evt);
            }
        });

        player2Field.setText("Player 2 Name");
        player2Field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                player2FieldFocusGained(evt);
            }
        });

        player3Field.setText("Player 3 Name");
        player3Field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                player3FieldFocusGained(evt);
            }
        });

        player4Field.setText("Player 4 Name");
        player4Field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                player4FieldFocusGained(evt);
            }
        });

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        gunung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monopoly/resources/newGameFrame.jpg"))); // NOI18N

        playerNameText.setText("Player Name:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numPlayerText)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPlayerCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playerNameText)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(player1Field, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(player2Field, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(player3Field, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(player4Field, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(okButton)
                .addGap(38, 38, 38))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gunung)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(gunung)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numPlayerText)
                    .addComponent(playerNameText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPlayerCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(player1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(player2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(player3Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(player4Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(okButton)
                        .addGap(34, 34, 34))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void player1FieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_player1FieldFocusGained
        player1Field.setText("");
    }//GEN-LAST:event_player1FieldFocusGained

    private void player2FieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_player2FieldFocusGained
        player2Field.setText("");
    }//GEN-LAST:event_player2FieldFocusGained

    private void player3FieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_player3FieldFocusGained
        player3Field.setText("");
    }//GEN-LAST:event_player3FieldFocusGained

    private void player4FieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_player4FieldFocusGained
        player4Field.setText("");
    }//GEN-LAST:event_player4FieldFocusGained

    private void jPlayerComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPlayerComboActionPerformed
        
        if (jPlayerCombo.getSelectedItem().equals("None")) {
            jPlayerCombo.setVisible(false);
            playerNameText.setVisible(false);
            player1Field.setVisible(false);
            player2Field.setVisible(false);
            player3Field.setVisible(false);
            player4Field.setVisible(false);     
        } if (jPlayerCombo.getSelectedItem().equals("1 Player")) {
            jPlayerCombo.setVisible(false);
            player1Field.setVisible(true);
            player2Field.setVisible(false);
            player3Field.setVisible(false);
            player4Field.setVisible(false);
            playerNameText.setVisible(true);
        } if (jPlayerCombo.getSelectedItem().equals("2 Players")) {
            jPlayerCombo.setVisible(false);
            player1Field.setVisible(true);
            player2Field.setVisible(true);
            player3Field.setVisible(false);
            player4Field.setVisible(false);
            playerNameText.setVisible(true);
        } if (jPlayerCombo.getSelectedItem().equals("3 Players")) {
            jPlayerCombo.setVisible(false);
            player1Field.setVisible(true);
            player2Field.setVisible(true);
            player3Field.setVisible(true);
            player4Field.setVisible(false);
            playerNameText.setVisible(true);
        } if (jPlayerCombo.getSelectedItem().equals("4 Players")) {
            jPlayerCombo.setVisible(false);
            player1Field.setVisible(true);
            player2Field.setVisible(true);
            player3Field.setVisible(true);
            player4Field.setVisible(true);
            playerNameText.setVisible(true);
        }
        
    }//GEN-LAST:event_jPlayerComboActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        playerNameText.setVisible(false);
        player1Field.setVisible(false);
        player2Field.setVisible(false);
        player3Field.setVisible(false);
        player4Field.setVisible(false);
    }//GEN-LAST:event_formComponentShown

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        if ((jPlayerCombo.getSelectedItem().equals("None")) || (jPlayerCombo.getSelectedItem().equals("1 Player"))) {
            PopUpFrame cantPlay = new PopUpFrame();
            cantPlay.setLocationRelativeTo(null);
            cantPlay.setVisible(true);
        } else {
            playerNumber = this.getPlayerNumber();
            player1Name = this.getPlayerName(1);
            player2Name = this.getPlayerName(2);
            player3Name = this.getPlayerName(3);
            player4Name = this.getPlayerName(4);
            this.setVisible(false);
        }
    }//GEN-LAST:event_okButtonActionPerformed
    
    //method utk keluar
    public String getPlayerName(int noPlayer) {
        if (noPlayer == 1) {
            return player1Field.getText();
        } if (noPlayer == 2) {
            return player2Field.getText();
        } if (noPlayer == 3) {
            return player3Field.getText();
        } if (noPlayer == 4) {
            return player4Field.getText();
        } else {
            return "IOERROR! PlayerName Not Found!";
        }
    }
    
    public int getPlayerNumber() {
        if (jPlayerCombo.getSelectedItem().equals("1 Player")) {
            return 1;
        } if (jPlayerCombo.getSelectedItem().equals("2 Players")) {
            return 2;
        } if (jPlayerCombo.getSelectedItem().equals("3 Players")) {
            return 3;
        } if (jPlayerCombo.getSelectedItem().equals("4 Players")) {
            return 4;
        } else {
            return 0;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewGame().setVisible(true);
            }
        });
    }
    
    //needed variable
    private int playerNumber;
    private String player1Name;
    private String player2Name;
    private String player3Name;
    private String player4Name;
    
    //needed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel gunung;
    private javax.swing.JComboBox<String> jPlayerCombo;
    private javax.swing.JLabel numPlayerText;
    private javax.swing.JButton okButton;
    private javax.swing.JTextField player1Field;
    private javax.swing.JTextField player2Field;
    private javax.swing.JTextField player3Field;
    private javax.swing.JTextField player4Field;
    private javax.swing.JLabel playerNameText;
    // End of variables declaration//GEN-END:variables
}
